### ISSUE TITLE
Support EHCache 2.4/2.6?

### ISSUE THREAD

**Issue by tarioch** [ehcache/ehcache-jcache#39]
It looks like ehcache-jcache does not support ehcache 2.4/2.6. 
Ehcache 2.4 on the other hand is the only ehcache version supported by hibernate 4.

https://hibernate.atlassian.net/browse/HHH-8732
and
https://github.com/hibernate/hibernate-orm/pull/643

So if I see this correctly it's not possible to have an application which is using both hibernate and ehcache and also use the jcache interface for application specific caches?

Did I miss something?

**Comment by tarioch** [comment]
For now I forked this and back ported the logic a bit to work with ehcache 2.4
It does not support the mxbean for statistics and also doesn't support setting a specific classloader.

But it still might be useful for someone: https://github.com/tarioch/ehcache-jcache

**Comment by alexsnaps** [comment]
Hey Patrick,
That doesn't pass the TCK then, does it?
Thanks,
Alex

**Comment by tarioch** [comment]
I didn't try and it could very well be  that it doesn't pass it, but for my current usage it's good enough.

**Comment by alexsnaps** [comment]
Right, not saying that's a huge issue necessarily, only something we can't
really support... ehcache-jcache has to remain TCK compliant.
